### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by smanel** [NESCent/popgenInfo#106]
I have the  the following messages in R -gstudio:
STEP 2

```r
remote_add(repo, 
            name = "NESCent", 
            url = "https://github.com/NESCent/popgenInfo.git")
Error in remote_add(repo, name = "NESCent", url = "https://github.com/NESCent/popgenInfo.git") : 
  Error in 'git2r_remote_add': Remote 'NESCent' already exists.
In addition: Warning message:
package ‘git2r’ was built under R version 3.2.3 
 
# Check our remotes
remotes(repo)
```

STEP 3

```r
checkout(repo, "master")
Error in .local(object, ...) : 
  Error in 'git2r_checkout_tree': 2 conflicts prevent checkout
```

Any idea? Can I continue?
In addition I work on my local folder and I have some "try" files. It is=t a problem? Do I need to remove them?

**Comment by zkamvar** [comment]
> Error in 'git2r_remote_add': Remote 'NESCent' already exists.

This error says that you already have the remote set up. If you look at the [introduction](http://nescent.github.io/popgenInfo/CONTRIBUTING_WITH_GIT2R.html#backgroundmotivation), you'll notice that the first two steps should only be done once.

> Error in 'git2r_checkout_tree': 2 conflicts prevent checkout

It's difficult to know what this means without knowing what the state of your repository is. Given your next comment:

> In addition I work on my local folder and I have some "try" files. 

I would say that this is a problem. **I think the easiest option is to delete your local repository and then start from [step 2](http://nescent.github.io/popgenInfo/CONTRIBUTING_WITH_GIT2R.html#step-2-clone-your-fork-to-your-computer).** If you have any new files, save them somewhere else and add them in during [step 5](http://nescent.github.io/popgenInfo/CONTRIBUTING_WITH_GIT2R.html#step-5-adding-content-committing-and-pushing). 

Does this help?

**Comment by smanel** [comment]
Yes, very helpful.

In step 4, I suggest to give the information on the name of the vignette and the branch when you give a  name to the branch :(good practice is to name it the same as your branch): I read it too late.

About step 5,  I can use command  lines in Gsudio too?

I can re-start directly from step 5? Or do I need to update something before?

**Comment by zkamvar** [comment]
> In step 4, I suggest to give the information on the name of the vignette and the branch when you give a name to the branch :(good practice is to name it the same as your branch): I read it too late.

Very good point. I will make sure to update this :+1: 

> About step 5, I can use command lines in Gsudio too?

Yes, these commands can be run in Rstudio (as I did in the video)

> I can re-start directly from step 5? Or do I need to update something before?

Because of the error messages above, I don't think you can start from step 5. You should delete the repository off your computer and start from step 2.

**Comment by smanel** [comment]
-I already re-start from step 2 and have now no error message. 
-I have created a new branch (as described in the vignette) but I have  pushed no  file (steps 5) (I am still working on the vignette).
-My question was when I am ready to commit my new file, where I need to start again: can I use the new branch that I have created but that it is empty? Or do I need to update my local repository and create a new branch? In this case I probably need to delete  the empty branch that I have created?

**Comment by zkamvar** [comment]
> My question was when I am ready to commit my new file, where I need to start again: can I use the new branch that I have created but that it is empty? 

:+1: Yes. When you want to add your new file, you should use that branch. 

Is this the new branch you are referring to: https://github.com/smanel/popgenInfo/tree/2016-01-18-spatial-stats ?

**Comment by smanel** [comment]
yes.
