### ISSUE TITLE
Capitalization of drop down menu

### ISSUE THREAD

**Issue by mmlopezu** [NESCent/popgenInfo#118]
I just noticed that 'users' and 'package development' drop down menus need to be homogenize in terms of capitalization.

**Comment by hlapp** [comment]
Can you be more specific? I see "Users" and "Package Developers", which doesn't seem inconsistent to me. Perhaps you mean something else?

**Comment by mmlopezu** [comment]
I mean, for example, 'Basic statistics' vs 'Basic Statistics'.

On Tue, Jan 26, 2016 at 11:05 AM, Hilmar Lapp <notifications@github.com>
wrote:

> Can you be more specific? I see "Users" and "Package Developers", which
> doesn't seem inconsistent to me. Perhaps you mean something else?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NESCent/popgenInfo/issues/118#issuecomment-175092917>.
>



-- 
Margarita M. López-Uribe
NSF Postdoctoral Fellow
Department of Entomology
and
Department of Applied Ecology
North Carolina State University
https://sites.google.com/a/cornell.edu/mm-lopez-uribe/
<https://sites.google.com/a/cornell.edu/margarita-m-lopez-uribe/>

**Comment by hlapp** [comment]
I see it now. Good point, this should be fixed to follow one convention.
