### ISSUE TITLE
Packages list versus vignettes and Docker container

### ISSUE THREAD

**Issue by hlapp** [NESCent/popgenInfo#122]
Should an effort be made to bring the [packages list](http://nescent.github.io/popgenInfo/PACKAGES.html) in synchrony with what is used in vignettes, and / or what gets installed into the [Rpopgen Docker container](https://github.com/NESCent/popgen-docker/blob/master/Rpopgen/Dockerfile)?

Right now there are packages mentioned (such as LEA) that are neither used in any of the vignettes, nor in the Docker container. And we may well have more packages used in the vignettes and the container than in this list.

**Comment by zkamvar** [comment]
I think this is a good idea. Once it's done at this point, it shouldn't be too hard to keep up-to-date with the docker image.

**Comment by zkamvar** [comment]
This has been addressed in #163
