### ISSUE TITLE
SummarySequenceData present on website, but not in repository

### ISSUE THREAD

**Issue by zkamvar** [NESCent/popgenInfo#126]
The SummarySequenceData vignette [still appears on the website] (http://nescent.github.io/popgenInfo/SummarySequenceData.html), but does not exist on the master branch of the repository. It appears that this vignette previously failed checks and was pushed to a development branch in #87 and #89. I think the course of action is to take it from the development branch, clean it up, and do a new pull request.

**Comment by zkamvar** [comment]
Additionally, it appears that old, outdated vignettes are retained on the website. Do we want this?

**Comment by hlapp** [comment]
I'm pretty certain we don't. It's a result of the way that the website gets built (which is by adding files to a clean slate, but the clean slate is not in version control).

I'll need to revisit how this works and see whether I can perhaps use rsync instead.

**Comment by zkamvar** [comment]
I'm going to open the outdated vignettes on website as a new issue. For this one, I want to focus specifically on resurrecting SummarySequenceData.Rmd

**Comment by zkamvar** [comment]
I'm adding this to the publication milestone because it is currently listed in the publication.

**Comment by hlapp** [comment]
> For this one, I want to focus specifically on resurrecting SummarySequenceData.Rmd

It has been resurrected 2 months ago, see 16b52608de7f5ed41d04d7b7c889248d9fff6535. This is on branch `summaryseqstats` (see https://github.com/NESCent/popgenInfo/blob/summaryseqstats/use/SummarySequenceData.Rmd). The tests currently fail for this vignette, which is why I wanted it off of master.

**Comment by hlapp** [comment]
I should also note that this is summarized in #89. Now that you separated out #127, what remains here that is not a duplicate of #89?

**Comment by zkamvar** [comment]
> I should also note that this is summarized in #89. Now that you separated out #127, what remains here that is not a duplicate of #89?

A lively discussion :joy: 

...I'll close this in favor of #89.
