### ISSUE TITLE
PopDiffSequenceData needs links to data

### ISSUE THREAD

**Issue by zkamvar** [NESCent/popgenInfo#131]
The [Population Differentiation of Sequence Data](http://nescent.github.io/popgenInfo/PopDiffSequenceData.html) vignette does not have any description or links to the data used. I'm assuming that `Ebom` does not stand for [E. bombieri](https://en.wikipedia.org/wiki/Enrico_Bombieri) :stuck_out_tongue_closed_eyes: 

Can you correct this, @mmlopezu?

**Comment by mmlopezu** [comment]
I will correct this before our meeting on February 9th. Thanks for noticing @zkamvar 

Ebom stands for Eulaema bombiformis :smile:

**Comment by zkamvar** [comment]
:+1: :bee:
