### ISSUE TITLE
Issues to be fixed before publication

### ISSUE THREAD

**Issue by zkamvar** [NESCent/popgenInfo#163]
Before publication, all vignettes and content should be ship shape. I will list issues here, no matter how small. **critical issues are bold**

## Vignettes

- [x] [Microsatellite basic statistics issues](http://nescent.github.io/popgenInfo/startMicrosatellite.html):
  - [x] **What's next link is broken**
  - [x] add message = FALSE to suppress package startup messages in package loading chunk
  - [x] Fis and Fst are mentioned, but not tested (Perhaps it can be copied from the SNP vignette)
  - [x] Assumptions should be list
  - [x] Some grammar/style needs to be fixed
  - [x] The object `Mydata` is not necessary as `hw.test()` works on genind objects.
- [x] [Start SNP](http://nescent.github.io/popgenInfo/StartSNP.html)
  - [x] Link to data set should span text beyond the word "here".
  - [x] grammar/style
- [x] [Differentiation SNP](http://nescent.github.io/popgenInfo/DifferentiationSNP.html)
  - [x] **What's next link is broken**
  - [x] Package declarations should be quoted
  - [x] Link to data set should span text beyond the word "here".
  - [x] **`set.seed()` needs to be called before `find.clusters()`** If it's not, the cluster assignment could be 5 or 6 clusters, making the statement in the text inaccurate.
  - [x] The statement "Five groups were finally detected and represented by the discriminant analysis. The 11 states are not the good level for population analysis. But we need to remember that we used only 20 SNPs to conduct the analysis." doesn't make much sense to me. Why would we say that the 11 stats are not good for population analysis?
  - [x] grammar/style
- [x] [SNP distances](http://nescent.github.io/popgenInfo/2015-05-18-Dist-SNP.html)
  - [x] Link to data set should span text beyond the word "here".
  - [x] `distgen()` in text should read `dist.gene()`
  - [x] remove mention of gstudio since the package is not being updated on CRAN
- [x] [Summary Stats for Sequences](SummarySequenceData.html) needs to be added or removed from menu and manuscript
- [x] [Population Differentiation Sequence](http://nescent.github.io/popgenInfo/PopDiffSequenceData.html)
  - [x] Data import section could utilize `apex::read.multiFASTA()`
  - [x]  Need reference for AMOVA ". Furthermore, it is possible to test hypotheses about differentiation by grouping subpopulations in a hierarchical structure (Ref)."

## Package Developement

- [x] [Data Formats](http://nescent.github.io/popgenInfo/DATAFORMATS.html) needs multiDNA and multiPhyDat added (@thibautjombart and @KlausVigo)
- [x] **[Packages Available in R](http://nescent.github.io/popgenInfo/PACKAGES.html) needs to be updated.** There are many sentence fragments for some reason (See #122)
- [x]  [Introduction](http://nescent.github.io/popgenInfo/DEVELOPER_INTRO.html) and [Developing R Packages](http://nescent.github.io/popgenInfo/PACKAGE_TUTORIALS.html) are fairly redundant. Probably should merge former into latter.

## Other

- [x] in [Contribution guidelines](CONTRIBUTING.md), remove "submit early" from best practices
- [x] [Getting Started](http://nescent.github.io/popgenInfo/GETSTARTED.html) is pretty bare. It needs at least a description of what those links are for.

**Comment by zkamvar** [comment]
Yes, this is a long list, BUT, many of these are small changes. I believe it would be best to create branches for each major point and do pull requests. @hlapp, does that sound reasonable?

**Comment by hlapp** [comment]
Yes, and awesome list! :+1:

**Comment by zkamvar** [comment]
I need @smanel's input for the Differentiation SNP vignette. What does this phrase mean?

> Five groups were finally detected and represented by the discriminant analysis. The 11 states are not the good level for population analysis. But we need to remember that we used only 20 SNPs to conduct the analysis.

**Comment by smanel** [comment]
I suggest to replace by:

With a subset of 20 SNPs, five groups were finally detected and represented by the discriminant analysis.

**Comment by zkamvar** [comment]
> With a subset of 20 SNPs, five groups were finally detected and represented by the discriminant analysis.

My concern with this is that the analysis shows that the groups are not well represented since there is a significant level of overlap: http://nescent.github.io/popgenInfo/DifferentiationSNP.html#unsupervised-clustering

Perhaps something like:

It's clear that a subset of 20 SNPs does not have a strong enough signal to separate the samples into distinct groups. What would happen if we used more SNPs?

**Comment by smanel** [comment]
Oh sorry. I do not check it again.
Yes of course. This is really better.

**Comment by hlapp** [comment]
All done, so closing this out.
