### ISSUE TITLE
Custom domain name

### ISSUE THREAD

**Issue by hlapp** [NESCent/popgenInfo#165]
We should think about giving the site a permanent custom domain name, which would help with memorability, and would isolate from any future move of the repo to a different organization or Git host.

Possible choices include the following:

* popgen.evoio.org
* popgen.evo.io
* popgen.nescent.org
* popgeninfo.org
* popgen.io

Of these, I have full (evoio.org, evo.io) or indirect (nescent.org) control over the domains, and adding a subdomain is easy and has no added cost. The last two require new domain registrations (and subsequent upkeep of those). Unfortunately, [popgen.info](http://popgen.info) is already taken.

There are also more creative ones :smile_cat: :

* popgen.ninja
* popgen.rocks
* popgen.yoga

**Comment by zkamvar** [comment]
For posterity, when we go with a new site, we'll have to go through and modify all of the direct links.

**Comment by zkamvar** [comment]
Also, I'm not married to having the Info at the end of our name, especially since a capital I and lowercase l are so easily confused.

**Comment by zkamvar** [comment]
That being said, I'm partial to popgen.nescent.org to tie it back to the hackathon.

**Comment by hlapp** [comment]
As we are getting closer to submission, we should make a decision here.

@coughls, @smanel, @mmlopezu, @grunwald - any thoughts, preferences, other suggestions, or votes?

**Comment by smanel** [comment]
I like the creative one, but It can afraid people.
So  I vote for 

popgen.nescent.org

But is popgen.org not available (shorter?)

**Comment by mmlopezu** [comment]
I can't see the options, but I am ok with whatever the collective decides!

Margarita

On Mon, Mar 14, 2016 at 3:31 AM, Stéphanie Manel <notifications@github.com>
wrote:

> I like the creative one, but It can afraid people.
> So I vote for
>
> popgen.nescent.org
>
> But is popgen.org not available (shorter?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NESCent/popgenInfo/issues/165#issuecomment-196182476>.
>



-- 
Margarita M. López-Uribe
NSF Postdoctoral Fellow
Department of Entomology
and
Department of Applied Ecology
North Carolina State University
https://sites.google.com/a/cornell.edu/mm-lopez-uribe/
<https://sites.google.com/a/cornell.edu/margarita-m-lopez-uribe/>

**Comment by hlapp** [comment]
> But is popgen.org not available (shorter?)

It's been taken since 2001. The site seems currently down, but you can [see on the Internet Archive](https://web.archive.org/web/20140104212948/http://popgen.org/) what at least it used to be until recently.

**Comment by coughls** [comment]
I like popgen.nescent.org as well.

**Comment by zkamvar** [comment]
> It's been taken since 2001. The site seems currently down, but you can see on the Internet Archive what at least it used to be until recently.

I like their greeting on the side panel. Do you think we should use their JS for our front page? :laughing: 

```html
<font face="arial" size="1" color="red">
<script language="JavaScript">
<!--
document.write("<font color=green size=-1>")
day = new Date()
hr = day.getHours()
if (hr ==1)
document.write("Good morning!   1AM and still your going! ")
if (hr ==2)
document.write("Hey, it's past  2AM!   The bars must be closed!")
if (hr ==3)
document.write("Hey, it's after  3AM!   Are you a vampire or what?")
if (hr ==4)
document.write("4AM?  You must roam all night huh!")
if (hr ==5)
document.write("Whoa! It's almost daylight and your still going!")
if (hr ==6)
document.write("Hey, isn't it  too early to be using your computer")
if ((hr == 6) || (hr ==7) || (hr ==8) || (hr == 9) || (hr ==10))
document.write("Good Morning! Welcome to the web!")
if (hr ==11)
document.write("11AM... What are you doing surfing web so early??")
if (hr ==12)
document.write("NOON!  Great, it must be time for breakfast!")
if (hr ==13)
document.write("1PM  Ooops!  You missed breakfast, don't miss lunch!")
if (hr ==14)
document.write("It's 2PM. Have you eaten lunch yet or you missed it also??")
if ((hr==15) || (hr==16))
document.write("Good Afternoon! Surfing already?")
if ((hr==17) || (hr==18) || (hr==19) || (hr==20) || (hr==21) || (hr==22))
document.write("Good Evening! Welcome to prime time on the web in the new millenium!")
if (hr==23)
document.write("It's almost midnight... Aren't you sleepy yet?")
if (hr==0)
document.write("It's midnight... do you ever sleep?")
document.write("</font>")
// -->
</script>
</font>
```

**Comment by mmlopezu** [comment]
My vote is for: popgen.nescent.org

Margarita

On Mon, Mar 14, 2016 at 12:19 PM, Zhian N. Kamvar <notifications@github.com>
wrote:

> It's been taken since 2001. The site seems currently down, but you can see
> on the Internet Archive what at least it used to be until recently.
>
> I like their greeting on the side panel. Do you think we should use their
> JS for our front page? [image: :laughing:]
>
> <font face="arial" size="1" color="red"><script language="JavaScript"></script>
> </font>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NESCent/popgenInfo/issues/165#issuecomment-196392316>.
>



-- 
Margarita M. López-Uribe
NSF Postdoctoral Fellow
Department of Entomology
and
Department of Applied Ecology
North Carolina State University
https://sites.google.com/a/cornell.edu/mm-lopez-uribe/
<https://sites.google.com/a/cornell.edu/margarita-m-lopez-uribe/>

**Comment by hlapp** [comment]
Site is live now at http://popgen.nescent.org after DNS changes have been made.

**Comment by hlapp** [comment]
I am going to tentatively close this issue. Although personally I wouldn't have leaned to a subdomain of nescent.org (mainly because the main website, nescent.org, doesn't have a long-time presence), all preferences and votes stated were unanimously for popgen.nescent.org. Hence, while we can go back at any time and revise the choice, the unanimity behind popgen.nescent.org suggests we're going to want to stick with it.
