### ISSUE TITLE
adjust for update to apex

### ISSUE THREAD

**Issue by zkamvar** [NESCent/popgenInfo#176]
The apex package is going to update soon (See: https://github.com/thibautjombart/apex/issues/46). With this update comes a change to the accessor `locusNames()`. It has now been changed to `getLocusNames()` and `setLocusNames()`. This will have to change in these two lines: https://github.com/NESCent/popgenInfo/blame/cb0d66460c062ff8e2990c185b7f737f69f54050/use/PopDiffSequenceData.Rmd#L50-L51

The pull request should only be initiated once apex is on CRAN and the Docker container is rebuilt

**Comment by zkamvar** [comment]
Apex has been updated. As soon as the docker container is updated, we should create a pull request from the apex-update branch.

**Comment by hlapp** [comment]
I triggered a rebuild, succeeded. Submitted pull request, see #181. Triggered re-run of the CI test.

**Comment by hlapp** [comment]
I believe this is done.
