### ISSUE TITLE
Clean up team page on hackathon repo

### ISSUE THREAD

**Issue by hlapp** [NESCent/popgenInfo#19]
_(I am posting this here in lieu of creating a mailing list that reaches the group of members.)_

Our [Team page on the hackathon repo](https://github.com/NESCent/r-popgen-hackathon/wiki/Team-1) needs a little cleanup:

* [x] Clean up and update the [Products section](https://github.com/NESCent/r-popgen-hackathon/wiki/Team-1#products). Should list explicitly by name or title the workflow vignettes currently in the works or already committed. 
* [x] Clean up [Status section](https://github.com/NESCent/r-popgen-hackathon/wiki/Team-1#status). Perhaps this can just be removed? Is there infomation we still need post-hackathon?
* [x] [Biological questions](https://github.com/NESCent/r-popgen-hackathon/wiki/Team-1#biological-questions) should be transferred to issue tracker here (if that hasn't happened already).
* [x] Consolidate the [Goals section](https://github.com/NESCent/r-popgen-hackathon/wiki/Team-1#goals) as a simple succinct statement of what this team set out to accomplish. Move details to issue tracker here, to the extent that hasn't happened yet.

**Comment by hlapp** [comment]
I cleaned up and updated the Products section. Could others enumerate the workflow vignettes?

**Comment by zkamvar** [comment]
I believe that the status section can stay as it is. It does serve as a reference for where we were.

**Comment by hlapp** [comment]
@zkamvar will transfer biological questions to issues on the popgenInfo repo tracker.

**Comment by zkamvar** [comment]
DONE!
