### ISSUE TITLE
Add menu link for LMM Genetic Diversity vignette

### ISSUE THREAD

**Issue by hlapp** [NESCent/popgenInfo#190]
Need to add menu link for new LMM Genetic Diversity vignette, see #182. @panastheod [suggests](https://github.com/NESCent/popgenInfo/pull/182#issuecomment-229796625) "Comparing genetic diversity using mixed models" as the menu text.

**Comment by zkamvar** [comment]
There's also the matter of copy-editing, which I will include here as well.
