### ISSUE TITLE
Builds fails after CRAN package update

### ISSUE THREAD

**Issue by hlapp** [NESCent/popgenInfo#193]
Our current `master` branch [fails to build](https://circleci.com/gh/NESCent/popgenInfo/552):

```
label: PCAdapt
Quitting from lines 102-129 (2016-01-26-SNP-selection.Rmd) 
Error in pcadapt(genotype, K = K, transpose = TRUE) : 
  Argument transpose is deprecated. Please refer to the latest vignette for further information.
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> pcadapt

Execution halted
make[1]: *** [2016-01-26-SNP-selection.html] Error 1
```

It seems odd that a deprecation results in an error, but I don't know enough about the details of the respective package. @zkamvar: any ideas how best to fix this?

**Comment by hlapp** [comment]
And FYI, the reason I reran the last ([previously successful](https://circleci.com/gh/NESCent/popgenInfo/550)) build was that the rpopgen container changed (see NESCent/popgen-docker#14) and was rebuilt.

**Comment by zkamvar** [comment]
I will look into this at some point, but I'm currently frantically finishing up my dissertation to turn in to my committee by Monday...

**Comment by zkamvar** [comment]
It's as I suspected: an API change. This is not the first time it's happened; see #184.

This package used to be able to take in a data matrix in the user's session, but it removed this capability and now relies solely on files created on the user's disk and wrapped the 'deprecation' notice in a `stop()`. I can add a fix by writing the matrix to a temporary file. Additionally, I'll write the maintainer, asking them to either reinstate the previous behavior (as they only bumped the patch version) or potentially update this vignette as they continue to make breaking changes.

**Comment by hlapp** [comment]
Is there an alternative package? Is there a good rationale for the API change, or is this rather erratic and given the history `pcadapt` isn't the best package for us to recommend to users?

**Comment by zkamvar** [comment]
I don't know if there is an alternative package for this explicit approach. @smanel originally submitted this vignette and might know.

**Comment by smanel** [comment]
At my knowledge, no alternative package for this approach.   I think that users are used to  matrix or dataframe!
I can also ask  to M. Blum if no answer from Keurcien.
