### ISSUE TITLE
Update to circle 2.0

### ISSUE THREAD

**Issue by zkamvar** [NESCent/popgenInfo#204]
CircleCI is sunsetting all 1.0 builds and migrating to 2.0: https://circleci.com/docs/2.0/migrating-from-1-2/

If we want to continue building after August, we should update the `circle.yml` file. 

From my experience [playing with] [Circle 2.0 yaml files], it seems that we can have the ability to save artifacts for download and include CRON jobs so that we aren't caught off guard when someone submits a vignette only to find it failed because another vignette can't be built. I'll open a couple of issues for that wishlist and tag this one. 

[playing with]: https://github.com/everhartlab/sclerotinia-366/pull/23
[Circle 2.0 yaml files]: https://github.com/everhartlab/sclerotinia-366/blob/master/.circleci/config.yml

**Comment by hlapp** [comment]
This was finally resolved and completed not with the merge of #212 but in a26dff2b6f10426c4bc84d7c21f3b1e18ebe9941. It took a few attempts to get the deployment step correct, which only happens on master.
