### ISSUE TITLE
Build website weekly

### ISSUE THREAD

**Issue by zkamvar** [NESCent/popgenInfo#205]
As part of #204, It's possible to schedule cron jobs in Circle 2.0. 

Official documentation: https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow

Here's a worked example: https://github.com/everhartlab/sclerotinia-366/blob/1f40f64720803689d9990290e464a9540b83f8c0/.circleci/config.yml#L95-L103

**Comment by hlapp** [comment]
Indeed we're in a position now to add this.

**Comment by zkamvar** [comment]
I've added a commit in another branch that attempts to add this.... just as GitHub is experiencing issues 🤦‍♂️. In the meantime, what time should the website be rebuilt, or, what would be the least inconvenient time to have to fix a stupid bug?

**Comment by hlapp** [comment]
> what time should the website be rebuilt, or, what would be the least inconvenient time to have to fix a stupid bug?

I don't think we need to put this at a time that would allow quickly fixing the issue; isn't the main goal to _surface_ the issue so we know about it, and can consider how to address it, before some poor vignette submitter is hit by it?

Given that, I'd put it in the wee hours of the US morning, say 2am US Eastern (which would be 11pm Pacific, and still before 9am in Europe).

**Comment by zkamvar** [comment]
Good point! I'll set it up for the wee hours of tomorrow morning (temporarily allowing this branch to build) and make a pull request.

**Comment by hlapp** [comment]
Fixed by #213, although I took out the weekly re-deployment step. @zkamvar can you reopen if you believe the weekly redeployment is important?
