### ISSUE TITLE
Build on master fails in 2018-03-27_RDA_GEA.Rmd

### ISSUE THREAD

**Issue by hlapp** [NESCent/popgenInfo#209]
Unfortunately, after merging #207 we have a build failure on master:

```
Quitting from lines 177-179 (2018-03-27_RDA_GEA.Rmd) 
Error in match.arg(display, c("sites", "species", "wa", "lc", "bp", "cn",  : 
  'arg' must be NULL or a character vector
Calls: <Anonymous> ... NextMethod -> plot.cca -> scores -> scores.rda -> match.arg
```

Not sure how this could be with the build succeeding on the branch. @zkamvar or @BrennaF any clues?

**Comment by zkamvar** [comment]
I suspect it may be working from an old version of the docker container? I'm going to rebuilt it and ssh in to see what may be the problem.

**Comment by zkamvar** [comment]
I believe it has to do with the cache.

Here's the hash for the container used on Master:

```
Step 0 : FROM hlapp/rpopgen:latest
 ---> 258606beeaf4
Step 1 : MAINTAINER Hilmar Lapp hilmar.lapp@duke.edu
 ---> Using cache
 ---> 8029e3fde8a7
Successfully built 8029e3fde8a7
```

Whereas the PR had to download a new container:

```
Status: Downloaded newer image for hlapp/rpopgen:latest
 ---> 6d88b41435fa
Step 1 : MAINTAINER Hilmar Lapp hilmar.lapp@duke.edu
 ---> Running in af1775ae073a
 ---> 11a38192f971
Error removing intermediate container af1775ae073a: Cannot destroy container af1775ae073aa0d55c4fad39eef9d240ff0f51cb5822ee264bd9463181ccd03a: Driver btrfs failed to remove root filesystem af1775ae073aa0d55c4fad39eef9d240ff0f51cb5822ee264bd9463181ccd03a: Failed to destroy btrfs snapshot: operation not permitted
Successfully built 11a38192f971
```

**Comment by zkamvar** [comment]
I'm starting the build without the cache to see if it takes.

**Comment by zkamvar** [comment]
Okay it failed 🤦‍♂️ 

I'm pulling the latest container now, but it may take a while as I am on a pretty poor internet connection.

**Comment by zkamvar** [comment]
Though, I suspect it has to do with the fact that the new vegan was released yesterday and it was only today that the container picked it up.

**Comment by hlapp** [comment]
> I suspect it has to do with the fact that the new vegan was released yesterday and it was only today that the container picked it up.

That seems the most likely cause to me 😃
