### ISSUE TITLE
Build fails due to changes in devtools package

### ISSUE THREAD

**Issue by hlapp** [NESCent/popgenInfo#217]
The error occurs in the following chunk: https://github.com/NESCent/popgenInfo/blob/2bf7239c6367e2f80cb0147f3e332f4b83027709/develop/package_basics.Rmd#L180-L182

The error is the following:
```
Error in create(path) : could not find function "create"
```
Apparently something in devtools changed that requires fixing the chunk.

However, it may be worth considering to obsolete almost the whole article, and to link instead to the recently published [rOpenSci package development handbook](https://devguide.ropensci.org/building.html).

@zkamvar any thoughts here?

**Comment by zkamvar** [comment]
I would agree to label it as obsolete and just point to the rOpenSci book. I can make a PR to issue the death knell for that page and update the landing page if you'd like.

**Comment by hlapp** [comment]
Yes please 👍

**Comment by hlapp** [comment]
@zkamvar did you get around to changing anything? I don't see a new commit or PR. Or did you wave a magic wand? Magically the weekly build started working again: https://circleci.com/gh/NESCent/popgenInfo/700
