### ISSUE TITLE
Discussions on the look and feel of the website

### ISSUE THREAD

**Issue by zkamvar** [NESCent/popgenInfo#22]
Hi all, 

@grunwald made an observation to me yesterday that this site has the exact same look, feel, and title as our lab's [primer on population genetics](http://grunwaldlab.github.io/Population_Genetics_in_R/), which we utilize for workshops. 

The reason for this similarity is not an accident, I deliberately copied the configuration file from that website into this repository so that we would have a scaffold from which to build off of. I think now that we have a better idea of how the site will work, we can focus on how it will look.

- Here are some guidelines regarding themes immediately available to us: http://rmarkdown.rstudio.com/html_document_format.html#appearance-and-style (note that they are using the "united" theme and we are using the "readable" theme).

- Here are prepackaged themes to browse: https://bootswatch.com/ (some of them we will explicitly have to download, but it should not be too much trouble)

Please look through these themes and we will discuss what theme we want during our google hangout next week.

**Comment by mmlopezu** [comment]
Hi Zhian,

That is a very good point. I did not understand well the link the styles in the link that you sent but I agree that our website should look different that the primer on population genetics.

Margarita

**Comment by zkamvar** [comment]
When we meet next week, I can go over what these things mean briefly.

Zhian

**Comment by coughls** [comment]
I like the Cerulean, Sandstone and Spacelab themes but that's just my preference. They are all nice really!
Simone

**Comment by zkamvar** [comment]
After the group discussion today: Superhero theme. I'll try to get that up sometime today.

**Comment by zkamvar** [comment]
![image](https://cloud.githubusercontent.com/assets/3639446/7036241/cc9c87d2-dd46-11e4-97ce-bd50cfc85db8.png)

This is what superhero theme looks like.

**Comment by zkamvar** [comment]
![image](https://cloud.githubusercontent.com/assets/3639446/7036257/15bc6b8a-dd47-11e4-9243-afcce448fc68.png)
Spacelab theme

**Comment by zkamvar** [comment]
![image](https://cloud.githubusercontent.com/assets/3639446/7036275/517e20e6-dd47-11e4-9f3d-6bb7a0f618f6.png)
Cerulean

**Comment by zkamvar** [comment]
I can't get Sandstone to work, but that's because my css-fu is not very good at the moment.

**Comment by zkamvar** [comment]
Personally, I like cerulean :)

**Comment by hlapp** [comment]
I like Spacelab :smile:

**Comment by mmlopezu** [comment]
Either cerulean or spacelab :)

On Tue, Apr 7, 2015 at 9:23 PM, Hilmar Lapp <notifications@github.com>
wrote:

> I like Spacelab [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NESCent/popgenInfo/issues/22#issuecomment-90773929>.
>



-- 
Margarita M. López-Uribe
Postdoctoral Researcher
Department of Entomology
North Carolina State University
https://sites.google.com/a/cornell.edu/mm-lopez-uribe/
<https://sites.google.com/a/cornell.edu/margarita-m-lopez-uribe/>

**Comment by zkamvar** [comment]
:scream_cat: It's a tie!

**Comment by zkamvar** [comment]
I went with spacelab and am going to close this issue :space_invader:
