### ISSUE TITLE
Contributing guidelines should include naming conventions.

### ISSUE THREAD

**Issue by hlapp** [NESCent/popgenInfo#25]
For example,

* CamelCase or underscores to separate tokens? (We seem to be using CamelCase right now.)
* Some recommendation for a pattern that names should follow?
* Don't include words that signify facts that are implied. E.g., by definition, `Rmd` documents in one of the subdirectories are vignettes, hence no need to indicate that in the name. (And in the rare event that one is not, the name of that should indicate what it is.)

Other thoughts? Or is this overthinking it now?

**Comment by zkamvar** [comment]
@hlapp, are you referring to naming conventions of vignettes? 

This is important to consider since there are topics that could span multiple vignettes, but differ by marker. How about the convention of:

*date_author_subject.Rmd*

where the date is in **yyyymmdd** format, the author is **firstnamelastname**, and subject is **datasubject**.

For example, a vignette about discriminant analysis of principal components with SNP data by Thibaut would be:

*20150324_thibautjombart_snpdapc.Rmd*

Thoughts?

Additionally, should we point people to a common coding style? [This style, for example?](http://adv-r.had.co.nz/Style.html) Encouraging a common style would make the site look more consistent.

**Comment by hlapp** [comment]
Yes, naming conventions of vignettes. I wouldn't include date or author. 
* Re: date, which date - that of first draft, full draft, or acceptance? And I'm not sure how the date would add meaning to a vignette's file name. 
* Re: author, what if there is more than one author. What if other authors than the initial one end up writing more content in the end? What would you want an author name in the file name signify in a way that isn't redundant with the `author:` metadata attribute and version control?

I think we shouldn't think about vignettes as largely static documents that get mostly written once, by one person. I'd expect them to collaboratively evolve over time and become increasingly better. I think conventions we instate should honor that, i.e., make the barrier to initial submissions of first drafts low, and encourage future improvements by others.

**Comment by hlapp** [comment]
> Additionally, should we point people to a common coding style? [This style](http://adv-r.had.co.nz/Style.html), for example? Encouraging a common style would make the site look more consistent.

I'd be in favor, for the reason you say, and because it's one that makes contribution easier (less to think about for contributors that isn't core to the vignette subject) rather than harder.

**Comment by zkamvar** [comment]
> Re: author, what if there is more than one author. What if other authors than the initial one end up writing more content in the end? What would you want an author name in the file name signify in a way that isn't redundant with the author: metadata attribute and version control?

Your point on the author redundancy and limitation is a good one. It does make more sense to allow others to modify previous vignettes as they will have to be updated with package updates. 

> Re: date, which date - that of first draft, full draft, or acceptance? And I'm not sure how the date would add meaning to a vignette's file name.

Clarifying on date, this would give a unique identifier to a vignette (it is not impossible to imagine two authors writing different vignettes with the same title by accident). I think date of submission would be the best approach if we decided to utilize it.

**Comment by hlapp** [comment]
> Clarifying on date, this would give a unique identifier to a vignette (it is not impossible to imagine two authors writing different vignettes with the same title by accident).

Good point.

> I think date of submission would be the best approach if we decided to utilize it.

Actually, if to be used for helping to create a unique filename, shouldn't then the date of first commit be used? Because otherwise you'd have to change the filename subsequently (which isn't hard, but I'm wondering why to build the necessity for that into the process).

**Comment by zkamvar** [comment]
By date of submission, I did mean date of first commit. Whoops.

**Comment by zkamvar** [comment]
addressed in cb81a20

**Comment by hlapp** [comment]
I don't think you included a [note on style as per above](https://github.com/NESCent/popgenInfo/issues/25#issuecomment-85751245) in #69. Did you decide on dropping that part for now (which I would not object to), or was that accidental?

**Comment by hlapp** [comment]
Closing this issue as the naming convention part (which this issue is about) was address in #69.
