### ISSUE TITLE
Wishlist for future tutorials

### ISSUE THREAD

**Issue by zkamvar** [NESCent/popgenInfo#3]
These tutorials should be listed in the index file for the tutorials, but not linked until they are completed.
- [ ] Parentage analysis (broken out to #48) 
    - kinship coefficient
- [ ] Clustering
    - hybridization
    - introgression
- [ ] Population Differentiation 
    - Fst 
    - AMOVA
    - DAPC
- [ ] Effective population size
- [ ] Simulations
- [ ] Spatial and Landscape Analysis
   - Mantel
   - Barrier (Monomier/Wombling)
   - IBD
- [ ] phylogeography | @mmlopezu 
- [ ] DNA sequences

**Comment by zkamvar** [comment]
From Margarita: 

- [ ] phylogeography

**Comment by smanel** [comment]
We miss sections (see biological questions), but do we want to be exhaustive now?

**Comment by zkamvar** [comment]
When it comes to biological questions, it is valuable to be exhaustive regarding those. We do not need to be exhaustive regarding specific examples.

**Comment by hlapp** [comment]
Consolidated phylogeography (from @mmlopezu) into checklist, and removed separate comment as a clean up.

**Comment by hlapp** [comment]
I'd like to suggest that we break all of these out into separate issues. That makes it easy to tag, find, and discuss them, as well as to follow their implementation.

**Comment by zkamvar** [comment]
This will be closed once we find issues for each item.

**Comment by grunwald** [comment]
Extracted ea h issue into a single issue and closed this issue

**Comment by grunwald** [comment]
Extracted each issue into a single issue and closed this issue

**Comment by grunwald** [comment]
Extracted each issue into a single issue and closed this issue
