### ISSUE TITLE
List of Things To Do - After meeting 7Apr15

### ISSUE THREAD

**Issue by mmlopezu** [NESCent/popgenInfo#33]
* [x] Changing the look of the website
* [x] Create a vignette for the format of vignettes
* [x] Create .Rmd files with links to other websites
* [x] Link information from Software Carpentry about how to use Github (see #34)
* [x] Eat our own dog food
* [x] Add a section to the bottom of all vignettes where there is a list of all contributors 
* [x] Create a discussion about citations (knitcitations? doi? pubmed id?) (see #40)
* [x] Add an issue for all vignettes that are under development

**Comment by zkamvar** [comment]
I will take charge of changing the look of the website and I will also look into adding a section at the bottom of vignettes for contributors (from the YAML data).

**Comment by coughls** [comment]
Sorry I was stuck in another meeting that ran over yesterday so couldn't make the hangout! Will make the next one!

**Comment by mmlopezu** [comment]
I will create .Rmd files to link to other websites or blogs

@zkamvar - how do you create the checkboxes next to the list of items?

**Comment by hlapp** [comment]
> how do you create the checkboxes next to the list of items?

    * [ ] text

See [Github docs](https://help.github.com/articles/writing-on-github/#task-lists).

**Comment by mmlopezu** [comment]
Thanks!

On Wed, Apr 8, 2015 at 10:28 AM, Hilmar Lapp <notifications@github.com>
wrote:

> how do you create the checkboxes next to the list of items?
>
> * [ ] text
>
> See Github docs
> <https://help.github.com/articles/writing-on-github/#task-lists>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NESCent/popgenInfo/issues/33#issuecomment-90932777>.
>



-- 
Margarita M. López-Uribe
Postdoctoral Researcher
Department of Entomology
North Carolina State University
https://sites.google.com/a/cornell.edu/mm-lopez-uribe/
<https://sites.google.com/a/cornell.edu/margarita-m-lopez-uribe/>

**Comment by hlapp** [comment]
I think these are all either completed, or broken out into their own issues and tracked separately.
