### ISSUE TITLE
User section structure

### ISSUE THREAD

**Issue by zkamvar** [NESCent/popgenInfo#54]
Question from @smanel from #46:

>In the user section, I am wondering if it would not be more easy to replace workflow by the topic/biolgical questions that we have already. Workflow was a basic idea, but they are a little complicate to create. They will be within vignette.

**Comment by zkamvar** [comment]
I think this is a good idea. Each vignette will be an exploration of a particular topic and does not necessarily have to be constrained by being in a single-dataset workflow format. Thoughts?

**Comment by smanel** [comment]
If no objection, I will tranform the vignette "Creating and submitting workflow vignettes" and  creating and submitting vignettes and I will make the appropriate modifications?

**Comment by zkamvar** [comment]
I have no objection. Please make a separate branch and create a pull request for the modifications.

**Comment by zkamvar** [comment]
This issue concerns modification of CONTRIBUTING.md. Issues #25, #39, #59, and #60 also have to do with modifying CONTRIBUTING.md. Because these are all small changes, I will create a branch from @smanel's branch and modify the issues labeled above.

**Comment by hlapp** [comment]
@zkamvar I think you meant #69 to address this in full, so I am closing it for now. Reopen if that was misinterpreting or if I was missing some piece that remains pending in this one.
