### ISSUE TITLE
Parentage analysis vignette

### ISSUE THREAD

**Issue by grunwald** [NESCent/popgenInfo#68]
- kinship coefficient

**Comment by grunwald** [comment]
As per @mmlopezu's suggestions, ideally we can convince Pew et al to contribute this vignette. @mmlopezu will contact them once we're ready with contribution documentation, templates, etc.

**Comment by hlapp** [comment]
@grunwald isn't this a duplicate of #48? Or do you have a reason to have both?

**Comment by grunwald** [comment]
Yes. I extracted it from the long list of bulk issues not realizing this was already posted as a separate issue. Closing this one.
