### ISSUE TITLE
Schedule and coordinate vignette development sprints 

### ISSUE THREAD

**Issue by hlapp** [NESCent/popgenInfo#77]
We will need to have several development sprints to get the vignettes into shape that are to be included in the publication.

**Comment by smanel** [comment]
I will work on a vignette based on the use of  correlations among SNP frequencies and environmental variables to detect the signal of selection.

**Comment by hlapp** [comment]
I think this is complete, at least for the purposes of the publication?

**Comment by zkamvar** [comment]
This is indeed complete. It was added in #121
